Description: |
  This module creates a secure bucket and related resources
Parameters:
  CreateLogBucket:
    Type: Boolean
Conditions:
  HasLogBucket: !Equals
    - !Ref CreateLogBucket
    - true
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: !Ref RetentionPolicy
    Properties:
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
             SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: test-tag
          Value: test-value1
  LogBucket:
    Type: AWS::S3::Bucket
    Condition: HasLogBucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref LogBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

