Parameters:
  Foo:
    Type: String

Resources:
  Bucket1:
    Type: AWS::S3::Bucket
    Metadata:
      Rain:
        IfParam: Foo
    Properties:
      BucketName: Bucket1
  Bucket2:
    Type: AWS::S3::Bucket
    Metadata:
      Rain:
        IfNotParam: Foo
    Properties:
      BucketName: Bucket2

