Parameters:
  Name:
    Type: String
  BucketName:
    Type: String
Resources:
  Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Name
  Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

