Parameters:

  TableName:
    Type: String
  
  LambdaRole:
    Type: String
    Description: If set, allow the lambda function to access this table

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub ${TableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  LambdaPolicy:
    Type: AWS::IAM::RolePolicy
    Metadata:
      Comment: This resource is created only if the LambdaRoleArn is set
      Rain:
        IfParam: LambdaRoleArn 
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
            Effect: Allow
            Resource: 
              - !GetAtt Table.Arn
      PolicyName: !Sub ${TableName}-policy
      RoleName: !Ref LambdaRole

