on:
  push:
    tags:
    - 'm*'

name: Create a module release from tag

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: golang:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y zip

      - name: Build
        run: ./.github/workflows/modules.sh 

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/*

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4.1.7
        with:
          name: dist
          path: dist

      - run: |
          set -x
          (echo "${GITHUB_REF##*/}"; echo; git cherry -v "$(git describe --abbrev=0 HEAD^)" | cut -d" " -f3-) > CHANGELOG
          gh release upload "${GITHUB_REF##*/}" dist/modules.zip
          gh release upload "${GITHUB_REF##*/}" dist/modules.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

