on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Unit tests

env:
  GOFLAGS: "-buildvcs=false"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Lint
        run: |
          staticcheck ./...
          go vet ./...

      - name: Run unit tests
        run: go test ./...
